# Generated by Django 4.2.9 on 2024-02-01 13:18

from django.db import migrations, models

import core.mangers


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="useraccount",
            managers=[
                ("objects", core.mangers.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="birth_date",
            field=models.DateField(null=True),
        ),
    ]
