# Generated by Django 4.2.9 on 2024-02-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_useraccount_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="pesel",
            field=models.IntegerField(blank=True, max_length=11, null=True, unique=True, verbose_name="PESEL"),
        ),
    ]
