# Generated by Django 4.2.9 on 2024-02-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.CharField(max_length=150, verbose_name="Position")),
                ("city", models.CharField(max_length=25, verbose_name="City")),
                (
                    "payment",
                    models.FloatField(max_length=15, verbose_name="Payment per hour"),
                ),
                (
                    "job_description",
                    models.CharField(max_length=700, verbose_name="Job description"),
                ),
            ],
        ),
    ]
